version: '1.0'
name: master-pipeline
displayName: MasterPipeline
triggers:
  trigger: manual
  push:
    branches:
      include:
        - master
stages:
  - name: compile
    displayName: 编译
    strategy: naturally
    trigger: auto
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 20.12.1
        commands:
          - yarn config set registry https://registry.npm.taobao.org --global
          - yarn install
          - yarn build
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist/spa
        caches:
          - ~/.npm
        strategy: {}
      - step: publish@general_artifacts
        name: publish_general_artifacts
        displayName: 上传制品
        dependArtifact: BUILD_ARTIFACT
        artifactName: output
        strategy: {}
        dependsOn: build_nodejs
